services:
  webui-docker:
    build: /docker
    ports:
      - "${WEBUI_PORT:-27860}:7860"
    volumes:
      - models:/stable-diffusion-webui/models
      - ./data/outputs:/stable-diffusion-webui/outputs
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]
volumes:
  models:
