services:
  stable-diffusion-webui:
    build:
      context: /docker
      args:
          - PYTORCH_IMAGE_TAG
          - XFORMERS_TAG
          - WEBUI_VERSION
          - MIRROR_URL
    ports:
      - "${HTTP_PORT:-7860}:7860"
    volumes:
      - models:/stable-diffusion-webui/models
      - ./data/outputs:/stable-diffusion-webui/outputs
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                count: all
                capabilities: [compute, utility]
volumes:
  models:
